### ISSUE TITLE
I dont think its technically necessary to use create text node

### ISSUE THREAD

**Issue by Razpudding** [itemah26/HackYourFuture-JavaScript-HWks#5]
https://github.com/itemah26/HackYourFuture-JavaScript-HWks/blob/b29623e9b5a45e7bee49e8937ab60ec20addf111/week3/index.js#L8

It's not wrong, but it might be faster to use item.innerHTML = intead of document.createTextNode.

Nice job on the first 3 assignments btw

**Comment by itemah26** [comment]
done
