### ISSUE TITLE
You solutionw orks but is more complicated than it has to be

### ISSUE THREAD

**Issue by Razpudding** [itemah26/HackYourFuture-JavaScript-HWks#6]
https://github.com/itemah26/HackYourFuture-JavaScript-HWks/blob/b29623e9b5a45e7bee49e8937ab60ec20addf111/week3/index.js#L15

Now youre using objects nested inside an object inside an object (objectception!). A simpler way would be to have an array with objects inside it like so:

```
let list = [
  {
    id: "imagine_shoot_create",
    blah: "blah"
  },
  {
    id: "het_lightroom",
    blah: "blah"
  }
]
```
That way you can still find the right object in the array if you loop over it and check the id. If you want to be able to points straight to an object, this would alsow work:

```
let list = {
  imagine_shoot_create : {
    cover: "imagine_shoot_create.img",
    blah: "blah"
  },
  het_lightroom : {
    cover: "het_lightroom.img",
    blah: "blah"
  }
]
```

**Comment by itemah26** [comment]
yes, i will consider it in my next works
